# vim: ts=4 sw=4 sts=4 et ai

FROM ubuntu:18.04

WORKDIR /root

RUN \
    mkdir -p ~/.ssh && chmod -R 600 /root/.ssh && \
    touch /root/.ssh/known_hosts && \
    sed -i 's%archive.ubuntu.com%free.nchc.org.tw%' /etc/apt/sources.list && \
    apt update -y && \
    apt install -y --no-install-recommends \
        sudo wget curl ca-certificates aptitude \
        software-properties-common \
        ssh openssh-server openssh-client sshpass \
        most less dos2unix tree locales time man-db htop rsync \
        bash bash-completion \
        tar gzip zip bzip2 xz-utils p7zip-full \
        git tig \
        make automake autogen autoconf build-essential binutils pkg-config libtool \
        clang clang-tidy clang-format \
        gdb gdbserver cgdb \
        ninja-build ccache \
        python python3 python3-dev python3-pip ipython3 \
        sed bison flex \
        sysstat net-tools dstat strace ltrace \
        sysprof linux-tools-common linux-tools-generic \
        prelink astyle tmate valgrind \
        httpie \
    && \
    add-apt-repository -y ppa:jonathonf/vim && \
    add-apt-repository -y ppa:fish-shell/release-3 && \
    (apt update -y || true) && \
    apt install -y --no-install-recommends \
        vim \
        fish \
    && \
    ln -s /dev/shm /root/ramdisk && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*
